# Generated by Django 5.0.2 on 2024-07-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCollectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=25)),
                ('subject', models.CharField(choices=[('math', 'Matematika'), ('english', 'English'), ('russian', 'Rus tili'), ('chemist', 'Kimyo'), ('biology', 'Biologiya'), ('mothlang', 'Ona tili'), ('history', 'Tarix'), ('geography', 'Geografiya'), ('special', 'Maburiy testlar'), ('physics', 'Fizika')], max_length=20)),
                ('is_free', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Fanlardan test',
                'verbose_name_plural': 'Fanlardan testlar',
                'db_table': 'testcollectionmodel',
            },
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=25)),
                ('question', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='tests/')),
                ('answerA', models.TextField()),
                ('answerB', models.TextField()),
                ('answerC', models.TextField()),
                ('answerD', models.TextField()),
                ('answer_correct', models.CharField(default='', max_length=1)),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
                'db_table': 'testmodel',
            },
        ),
        migrations.CreateModel(
            name='DTMTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=25)),
                ('is_started', models.BooleanField(default=False)),
                ('testcollection', models.ManyToManyField(blank=True, to='dtmtest.testcollectionmodel')),
            ],
            options={
                'verbose_name': 'DTM test',
                'verbose_name_plural': 'DTM testlar',
                'db_table': 'dtmtest',
            },
        ),
        migrations.AddField(
            model_name='testcollectionmodel',
            name='tests',
            field=models.ManyToManyField(blank=True, to='dtmtest.testmodel'),
        ),
    ]
