# Generated by Django 5.0.2 on 2024-07-26 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtmtests', '0001_initial'),
    ]

    operations = [
    ]
